[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
cache = false
cache_path = 'forge-cache'
test = 'test'
gas_reports = ["ERC20"]
#optimizer = true
#optimizer_runs = 200
#via_ir = true
#memory_limit = 10000000000
fs_permissions = [{ access = "read-write", path = "./"}]
ffi = true

#remappings = [
#    'ds-test/=lib/forge-std/lib/ds-test/src/',
#    'forge-std/=lib/forge-std/src/',
#    '@openzeppelin/=lib/openzeppelin-contracts/'
#]

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"

[etherscan]
goerli = { key = "${GOERLI_SCAN_API_KEY}", url = "${GOERLI_ETHERSCAN_VERIFIER_URL}" }
optimism = { key = "${OPTIMISM_SCAN_API_KEY}", url = "${OPTIMISM_ETHERSCAN_VERIFIER_URL}" }